apiVersion: v1
kind: ReplicationController
metadata:
  name: go-hello
spec:
  replicas: 3
  selector:
    app: go-hello
  template:
    metadata:
      labels:
        app: go-hello
    spec:
      containers:
      - name: go-hello
        image: ariefdarmawan/go-hello
        ports:
        - containerPort: 10123