apiVersion: v1
kind: ReplicationController
metadata:
  name: go-hello
  labels:
    app: go-hello
spec:
  replicas: 3
  selector:
    app: go-hello
  template:
    metadata:
      labels:
        app: go-hello
    spec:
      containers:
      - name: go-hello
        image: ariefdarmawan/go-hello:latest
        ports:
        - containerPort: 10123
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: go-hello
spec:
  ports:
  - name: hello
    port: 10123
    protocol: TCP
    #nodePort: 30123
  type: LoadBalancer
  selector:
    app: go-hello
